---
- name: Retrieve OAI
  ansible.builtin.git:
    repo: https://gitlab.eurecom.fr/oai/cn5g/oai-cn5g-fed.git
    dest: oai-cn5g-fed
    version: v1.5.0
    force: yes

- name: Synchronize all git submodules
  shell: "./scripts/syncComponents.sh"
  args:
    chdir: oai-cn5g-fed

- name: Install Helm spray plugin
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/ThalesGroup/helm-spray
    plugin_version: v4.0.10
    state: present

- name: Create blueprint namespace 
  kubernetes.core.k8s:
    name: '{{ GCN.namespace }}'
    api_version: v1
    kind: Namespace
    state: present
  become: yes

- name: Setup 5G core
  ansible.builtin.include_tasks: 'core.yaml'
  when: GCN.core.present

- name: Setup RAN
  ansible.builtin.include_tasks: 'ran.yaml'
  when: GCN.RAN.present

- name: Setup UEs
  ansible.builtin.include_tasks: 'ue.yaml'
  when: GCN.UE.present