---
# k8s config
k8s:
  runtime: docker
  podSubnet: 10.244.0.0/16
  serviceSubnet: 172.23.0.0/24
  dnsDomain: cluster.local
  controlPlaneEndpoint: 192.168.0.1:6443
  #apiserver_advertise_address: 192.0.2.1
  calico:
    # nodeAddressAutodetectionV4:
    #   cidrs:
    #     - 192.0.2.0/24
  encapsulation: VXLAN
  metallb:
    addresses:
      - 172.21.10.203/32
