{{- if .Values.multus.create }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Chart.Name }}-net1
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": {{- cat .Values.multus.hostInterface | nospace | quote }},
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.IPadd "/" .Values.multus.Netmask | nospace | quote }}
                }
        ]
      }
    }'
{{- end }}
