debian_9_dependencies:
  - name: git
    state: present
  - name: conntrack
    state: present
  - name: python-pip
    state: present
  - name: curl
    state: present
  - name: apt-transport-https
    state: present
  - name: ca-certificates
    state: present
  - name: lsb-release
    state: present
  - name: patch
    state: present
  - name: wget
    state: present

debian_10_dependencies:
  - name: git
    state: present
  - name: conntrack
    state: present
  - name: python-pip
    state: present
  - name: python3-pip
    state: present
  - name: curl
    state: present
  - name: apt-transport-https
    state: present
  - name: ca-certificates
    state: present
  - name: lsb-release
    state: present
  - name: patch
    state: present
  - name: wget
    state: present

ubuntu_20_dependencies:
  - name: git
    state: present
  - name: conntrack
    state: present
  - name: python3-pip
    state: present
  - name: curl
    state: present
  - name: apt-transport-https
    state: present
  - name: ca-certificates
    state: present
  - name: lsb-release
    state: present
  - name: patch
    state: present
  - name: wget
    state: present

fedora_36_dependencies:
  - name: git
    state: present
  - name: conntrack
    state: present
  - name: python3-pip
    state: present
  - name: curl
    state: present
  - name: redhat-lsb
    state: present
  - name: iproute-tc
    state: present
  - name: wget
    state: present
  - name: dnf-plugins-core
    state: present
  - name:  zram-generator-defaults
    state: absent

python_packages:
    - name: docker
      version: 4.4.4
    - name: kubernetes
      version: 18.20.0