---
# 5G config
GCN:
  namespace: blueprint
  core:
    present: true
    custom_files: blueprint/files
    custom_values: blueprint/values
#  RAN:
#    present: true
#    custom_files: blueprint/ran_files
#    custom_values: blueprint/ran_values
#    split:
#      f1: false
#      e1: false
#  UE:
#    present: true
#    tests:
#      landmark_ping:
#          landmark: google.fr
