---
#registry config
registry_name: DATA+OMITTED
auth:
  - login: DATA+OMITTED
    password: DATA+OMITTED
  - login: DATA+OMITTED
    password: DATA+OMITTED
auth_file: DATA+OMITTED
path:
  certificate: DATA+OMITTED
  authentication: DATA+OMITTED

# k8s config
kube_config_local_path: DATA+OMITTED
master: DATA+OMITTED
subnet: DATA+OMITTED

# Fabric
fabric_profile: fabric-v1model fabric-tna

onos_applications:
  - name: org.onosproject.drivers.barefoot
  - name: org.onosproject.drivers.bmv2

netcfg:
  "device:sopnode-sw1":
    basic:
      managementAddress: "grpc://138.96.245.11:9559?device_id=1"
      driver: "stratum-tofino"
      pipeconf: "org.stratumproject.fabric.montara_sde_9_7_0"
  "device:sopnode-sw2":
    basic:
      managementAddress: "grpc://138.96.245.12:9559?device_id=1"
      driver: "stratum-tofino"
      pipeconf: "org.stratumproject.fabric.montara_sde_9_7_0"
  "device:sopnode-sw3":
    basic:
      managementAddress: "grpc://138.96.245.13:9559?device_id=1"
      driver: "stratum-tofino"
      pipeconf: "org.stratumproject.fabric.montara_sde_9_7_0"