apiVersion: v2
name: oai-5g-mini
type: application
icon: http://www.openairinterface.org/wp-content/uploads/2015/06/cropped-oai_final_logo.png
version: v1.5.1
description: OAI 5G Release 16 Core Network

appVersion: develop-v1.5.1

keywords:
  - 5GCN
  - AMF
  - SMF
  - NRF #Optional but if you want to remove please configure AMF, SMF and UPF with each others IP-Address
  - UPF

maintainers:
  - name:  OPENAIRINTERFACE
    email: contact@openairinterface.org

dependencies:
- condition: mysql.enabled
  name: mysql
  repository: "file://../mysql"
  version: 8.0.31
- condition: oai-nrf.enabled
  name: oai-nrf
  repository: "file://../oai-nrf"
  version: v1.5.1
- condition: oai-amf.enabled
  name: oai-amf
  repository: "file://../oai-amf"
  version: v1.5.1
- condition: oai-smf.enabled
  name: oai-smf
  repository: "file://../oai-smf"
  version: v1.5.1
- condition: oai-spgwu-tiny.enabled
  name: oai-spgwu-tiny
  repository: "file://../oai-spgwu-tiny"
  version: v1.5.1